### PR TITLE
[Imperative Programming] Fix missing Open Poly

### PR DESCRIPTION
**Pull request by g1eny0ung**
During reading the chapter of `imperative programming`, in section `Example: Doubly Linked Lists`, the code example in my local environment can't build as expected:

> let is_empty t = !t = None
Error: This expression has type 'a option but an expression was expected of type int

After searching, I found that the base library only exposes integer comparison by default. So, I add `open Poly` in:

```ocaml
let is_empty t = let open Poly in !t = None
```

Then the error disappeared.

### CODE REVIEW

**Comment by yminsky** [comment]
I'd rather fix this by avoiding polymorphic compare, rather than reintroducing it.  (You can see the section on the perils of polymorphic compare in this chapter for the reasoning: https://dev.realworldocaml.org/maps-and-hashtables.html)

Using Option.is_none instead should take care of it.  Would you mind approaching it that way instead?

**Comment by g1eny0ung** [comment]
I haven't read this chapter yet but I believe your approach is correct through your description.

```ocaml
let is_empty t = if Option.is_none !t then true else false
```

Amend it like this? If it is correct, I will update the PR.

**Comment by yminsky** [comment]
That will work, but even better would be:

```ocaml
let is_empty t = Option.is_none !t
```

**Comment by g1eny0ung** [comment]
Thx! Already updated.

**Pull request merged**
