### PR TITLE
Switch to opam-monorepo

### LINKED ISSUE #3407: Upgrade from duniverse to opam-monorepo
Duniverse is being replaced by an opam plugin: `opam monorepo`. It uses opam lockfiles instead of its own custom format.

As soon as v0.1.0 is released and we have support for it in ocaml-ci we should upgrade from duniverse to the plugin and update the documentation in the README regarding how to use it to upgrade RWO's lockfile and dependencies.

### PR DESCRIPTION
**Pull request by NathanReb**
Fix #3407 

I'm marking this as draft until I updated the README with a bit of documentation on how to work with opam-monorepo.

@emillon can use this to test the ocaml-ci counterpart to this change!

### CODE REVIEW

**Comment by emillon** [comment]
Thanks. I managed to get a green build but I had 2 fixes to make to this branch:
- the lock file is inconsistent with the opam file on `ocaml` (ocamllabs/duniverse#134)
- this PR switches the version of ctypes: in `dune-get` it used to point to `https://github.com/avsm/ocaml-ctypes.git#dune-port` (resolved to a186a0dd10b7a04ce8eec5c6b63b1d6865eaa21e) while the version in `rwo.opam.locked` is 96700a9886dfea4551192b2cc75de9d1e845b859. Maybe there are some local changes too. Concretely this means that I had to change references to ctypes-foreign.threaded to just ctypes-foreign, but I think that switching the ref would work instead.

**Comment by emillon** [comment]
There are some other changes in the duniverse folder. Most of them are related to the switch to release tarballs so hidden files are not included (fixed bug in dune-release - usually innocuous). There's also some metadata changes (version in dune-project files I suppose) and some code changes.

<details>
<summary>Here are the non-hidden files that changed</summary>

```
 duniverse/atd.2.2.1/atd/src/version.ml
 duniverse/atd.2.2.1/atdgen/src/deprecated/version.ml
 duniverse/atd.2.2.1/atdgen/src/version.ml
 duniverse/atd.2.2.1/doc/tutorial-data/untypable-json/untypable.atd
 duniverse/{atd.2.2.1 => atd}/atd.opam
 duniverse/atd/atd/src/version.ml
 duniverse/{atd.2.2.1 => atd}/atdgen-codec-runtime.opam
 duniverse/{atd.2.2.1 => atd}/atdgen-runtime.opam
 duniverse/{atd.2.2.1 => atd}/atdgen-runtime/src/version.ml
 duniverse/{atd.2.2.1 => atd}/atdgen.opam
 duniverse/atd/atdgen/src/deprecated/version.ml
 duniverse/atd/atdgen/src/version.ml
 duniverse/{atd.2.2.1 => atd}/atdj.opam
 duniverse/{atd.2.2.1 => atd}/atdj/test/json.jar
 duniverse/{atd.2.2.1 => atd}/atdj/test/junit-4.8.2.jar
 duniverse/{atd.2.2.1 => atd}/atds.opam
 duniverse/{atd.2.2.1 => atd}/atds/test/argonaut_2.11-6.2.2.jar
 duniverse/{atd.2.2.1 => atd}/atds/test/argonaut_2.12-6.2.2.jar
 duniverse/{atd.2.2.1 => atd}/atds/test/junit-4.8.2.jar
 duniverse/atd/doc/tutorial-data/untypable-json/untypable_v2.atd
 duniverse/{atd.2.2.1 => atd}/dune-project
 duniverse/{atd.2.2.1 => atd}/internal-doc/README.md
 duniverse/{biniou.1.2.1 => biniou}/biniou.opam
 duniverse/{biniou.1.2.1 => biniou}/dune-project
 duniverse/{bisect_ppx.2.4.1 => bisect_ppx}/doc/sample.gif
 duniverse/{core_kernel.v0.13.1 => core_kernel}/test/src/sample_time_zone_file
 duniverse/{cppo.1.6.6 => cppo}/cppo.opam
 duniverse/{cppo.1.6.6 => cppo}/cppo_ocamlbuild.opam
 duniverse/ctypes-foreign.0.17.1+dune/examples/date/foreign/dune
 duniverse/ctypes-foreign.0.17.1+dune/examples/fts/foreign/dune
 duniverse/ctypes-foreign.0.17.1+dune/examples/fts/stub-generation/bindings/dune
 duniverse/ctypes-foreign.0.17.1+dune/src/ctypes-foreign-threaded/dune
 duniverse/ctypes-foreign.0.17.1+dune/src/ctypes-foreign-unthreaded/ctypes_gc_mutex.ml
 duniverse/ctypes-foreign.0.17.1+dune/src/ctypes-foreign-unthreaded/dune
 duniverse/ctypes-foreign.0.17.1+dune/src/ctypes-foreign-unthreaded/foreign.ml
 duniverse/ctypes-foreign.0.17.1+dune/src/ctypes-foreign/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-arrays/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-bigarrays/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-bools/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-builtins/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-coercions/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-complex/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-cstdlib/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-higher_order/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-integers/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-lifetime/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-macros/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-oo_style/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-passable/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-pointers/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-raw/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/test-threads/dune
 duniverse/ctypes-foreign.0.17.1+dune/tests/tests-common/dune
 duniverse/{domain-name.0.3.0 => domain-name}/README.md
 duniverse/{domain-name.0.3.0 => domain-name}/domain-name.opam
 duniverse/{domain-name.0.3.0 => domain-name}/domain_name.mli
 duniverse/{domain-name.0.3.0 => domain-name}/dune-project
 duniverse/{dune-build-info.2.6.0 => dune_}/bin/subst.ml
 duniverse/{dune-build-info.2.6.0 => dune_}/dune-action-plugin.opam
 duniverse/{dune-build-info.2.6.0 => dune_}/dune-build-info.opam
 duniverse/{dune-build-info.2.6.0 => dune_}/dune-configurator.opam
 duniverse/{dune-build-info.2.6.0 => dune_}/dune-glob.opam
 duniverse/{dune-build-info.2.6.0 => dune_}/dune-private-libs.opam
 duniverse/{dune-build-info.2.6.0 => dune_}/dune-project
 duniverse/{dune-build-info.2.6.0 => dune_}/dune.opam
 duniverse/{dune-build-info.2.6.0 => dune_}/test/blackbox-tests/test-cases/workspace-paths/bin/hello.exe.source
 duniverse/{duration.0.1.3 => duration}/README.md
 duniverse/{duration.0.1.3 => duration}/dune-project
 duniverse/{duration.0.1.3 => duration}/duration.mli
 duniverse/{duration.0.1.3 => duration}/duration.opam
 duniverse/{easy-format.1.3.2 => easy-format}/dune-project
 duniverse/{easy-format.1.3.2 => easy-format}/easy-format.opam
 duniverse/{eqaf.0.7 => eqaf}/dune-project
 duniverse/{eqaf.0.7 => eqaf}/eqaf.opam
 duniverse/{fiat-p256.0.2.1 => fiat}/dune-project
 duniverse/{fiat-p256.0.2.1 => fiat}/fiat-p256.opam
 duniverse/{gmap.0.3.0 => gmap}/README.md
 duniverse/{gmap.0.3.0 => gmap}/gmap.mli
 duniverse/{gmap.0.3.0 => gmap}/gmap.opam
 duniverse/{hacl_x25519.0.1.1 => hacl}/dune-project
 duniverse/{hacl_x25519.0.1.1 => hacl}/hacl_x25519.opam
 duniverse/{lambdasoup.0.7.1 => lambdasoup}/docs/sample.gif
 duniverse/{markup.0.8.2 => markup}/docs/sample.png
 duniverse/{mdx.1.7.0 => mdx}/bin/main.ml
 duniverse/{mdx.1.7.0 => mdx}/bin/test/main.ml
 duniverse/{mdx.1.7.0 => mdx}/dune-project
 duniverse/{mdx.1.7.0 => mdx}/mdx.opam
 duniverse/{mirage-crypto-pk.0.8.0 => mirage-crypto}/README.md
 duniverse/{mirage-crypto-pk.0.8.0 => mirage-crypto}/dune-project
 duniverse/{mirage-crypto-pk.0.8.0 => mirage-crypto}/mirage-crypto-pk.opam
 duniverse/{mirage-crypto-pk.0.8.0 => mirage-crypto}/mirage-crypto-rng-mirage.opam
 duniverse/{mirage-crypto-pk.0.8.0 => mirage-crypto}/mirage-crypto-rng.opam
 duniverse/{mirage-crypto-pk.0.8.0 => mirage-crypto}/mirage-crypto.opam
 duniverse/{mmap.1.1.0 => mmap}/mmap.opam
 duniverse/{asn1-combinators.0.2.2 => ocaml-asn1-combinators}/README.md
 duniverse/{asn1-combinators.0.2.2 => ocaml-asn1-combinators}/asn1-combinators.opam
 duniverse/{asn1-combinators.0.2.2 => ocaml-asn1-combinators}/dune-project
 duniverse/{asn1-combinators.0.2.2 => ocaml-asn1-combinators}/src/asn.mli
 duniverse/{base64.3.4.0 => ocaml-base64}/base64.opam
 duniverse/{base64.3.4.0 => ocaml-base64}/dune-project
 duniverse/{base64.3.4.0 => ocaml-base64}/src/base64.mli
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp-async.opam
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp-lwt-jsoo.opam
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp-lwt-unix.opam
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp-lwt.opam
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp-mirage.opam
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp-mirage/src/client.ml
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp-mirage/src/io.ml
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp-mirage/src/io.mli
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp-mirage/src/static.ml
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp-mirage/src/static.mli
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp-top.opam
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/cohttp.opam
 duniverse/{cohttp-async.2.5.1 => ocaml-cohttp}/dune-project
 duniverse/{conduit-async.2.1.0 => ocaml-conduit}/conduit-async.opam
 duniverse/{conduit-async.2.1.0 => ocaml-conduit}/conduit-lwt-unix.opam
 duniverse/{conduit-async.2.1.0 => ocaml-conduit}/conduit-lwt.opam
 duniverse/{conduit-async.2.1.0 => ocaml-conduit}/conduit-mirage.opam
 duniverse/{conduit-async.2.1.0 => ocaml-conduit}/conduit.opam
 duniverse/{conduit-async.2.1.0 => ocaml-conduit}/dune-project
 duniverse/{cstruct-sexp.5.1.1 => ocaml-cstruct}/README.md
 duniverse/{cstruct-sexp.5.1.1 => ocaml-cstruct}/cstruct-async.opam
 duniverse/{cstruct-sexp.5.1.1 => ocaml-cstruct}/cstruct-lwt.opam
 duniverse/{cstruct-sexp.5.1.1 => ocaml-cstruct}/cstruct-sexp.opam
 duniverse/{cstruct-sexp.5.1.1 => ocaml-cstruct}/cstruct-unix.opam
 duniverse/{cstruct-sexp.5.1.1 => ocaml-cstruct}/cstruct.opam
 duniverse/{cstruct-sexp.5.1.1 => ocaml-cstruct}/dune-project
 duniverse/{cstruct-sexp.5.1.1 => ocaml-cstruct}/ppx_cstruct.opam
 duniverse/{cstruct-sexp.5.1.1 => ocaml-cstruct}/ppx_test/http.cap
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/Makefile
 duniverse/ocaml-ctypes/examples/date/foreign/dune
 duniverse/ocaml-ctypes/examples/fts/foreign/dune
 duniverse/ocaml-ctypes/examples/fts/stub-generation/bindings/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/examples/fts/stub-generation/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/examples/fts/stub-generation/stub-generator/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/examples/ncurses/foreign/dune
 duniverse/{ctypes-foreign.0.17.1+dune/src/ctypes-foreign-base => ocaml-ctypes/src/ctypes-foreign}/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/clib/test_functions.h
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-alignment/dune
 duniverse/ocaml-ctypes/tests/test-arrays/dune
 duniverse/ocaml-ctypes/tests/test-bigarrays/dune
 duniverse/ocaml-ctypes/tests/test-bools/dune
 duniverse/ocaml-ctypes/tests/test-builtins/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-callback_lifetime/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-callback_lifetime/stubs/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-closure-type-promotion/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-closure-type-promotion/stubs/dune
 duniverse/ocaml-ctypes/tests/test-coercions/dune
 duniverse/ocaml-ctypes/tests/test-complex/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-constants/dune
 duniverse/ocaml-ctypes/tests/test-cstdlib/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-cstdlib/stubs/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-foreign-errno/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-foreign_values/dune
 duniverse/ocaml-ctypes/tests/test-higher_order/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-higher_order/stubs/dune
 duniverse/ocaml-ctypes/tests/test-integers/dune
 duniverse/ocaml-ctypes/tests/test-lifetime/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-lifetime/stubs/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-lwt-jobs/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-lwt-preemptive/dune
 duniverse/ocaml-ctypes/tests/test-macros/dune
 duniverse/ocaml-ctypes/tests/test-oo_style/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-oo_style/stubs/dune
 duniverse/ocaml-ctypes/tests/test-passable/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-passing-ocaml-values/dune
 duniverse/ocaml-ctypes/tests/test-pointers/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-pointers/stubs/dune
 duniverse/ocaml-ctypes/tests/test-raw/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-returning-errno-lwt-jobs/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-returning-errno-lwt-preemptive/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-returning-errno/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-roots/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-sizeof/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-structs/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-structs/stubs/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-stubs/dune
 duniverse/ocaml-ctypes/tests/test-threads/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-type_printing/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-unions/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-unions/stubs/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-value_printing/dune
 duniverse/{ctypes-foreign.0.17.1+dune => ocaml-ctypes}/tests/test-views/stubs/dune
 duniverse/ocaml-ctypes/tests/tests-common/dune
 duniverse/{hex.1.4.0 => ocaml-hex}/hex.opam
 duniverse/{hkdf.1.0.4 => ocaml-hkdf}/dune-project
 duniverse/{hkdf.1.0.4 => ocaml-hkdf}/hkdf.opam
 duniverse/{ipaddr-sexp.5.0.0 => ocaml-ipaddr}/dune-project
 duniverse/{ipaddr-sexp.5.0.0 => ocaml-ipaddr}/ipaddr-cstruct.opam
 duniverse/{ipaddr-sexp.5.0.0 => ocaml-ipaddr}/ipaddr-sexp.opam
 duniverse/{ipaddr-sexp.5.0.0 => ocaml-ipaddr}/ipaddr.opam
 duniverse/{ipaddr-sexp.5.0.0 => ocaml-ipaddr}/lib/ipaddr.mli
 duniverse/{ipaddr-sexp.5.0.0 => ocaml-ipaddr}/lib/ipaddr_unix.mli
 duniverse/{ipaddr-sexp.5.0.0 => ocaml-ipaddr}/lib/macaddr.mli
 duniverse/{ipaddr-sexp.5.0.0 => ocaml-ipaddr}/macaddr-cstruct.opam
 duniverse/{ipaddr-sexp.5.0.0 => ocaml-ipaddr}/macaddr-sexp.opam
 duniverse/{ipaddr-sexp.5.0.0 => ocaml-ipaddr}/macaddr.opam
 duniverse/{magic-mime.1.1.2 => ocaml-magic-mime}/dune-project
 duniverse/{magic-mime.1.1.2 => ocaml-magic-mime}/magic-mime.opam
 duniverse/{ocaml-migrate-parsetree.1.7.3 => ocaml-migrate-parsetree}/dune-project
 duniverse/{ocaml-migrate-parsetree.1.7.3 => ocaml-migrate-parsetree}/ocaml-migrate-parsetree.opam
 duniverse/{ocaml-print-intf.1.2.0 => ocaml-print-intf}/dune-project
 duniverse/{ocaml-print-intf.1.2.0 => ocaml-print-intf}/ocaml-print-intf.opam
 duniverse/{re.1.9.0 => ocaml-re}/re.opam
 duniverse/{uri-sexp.3.1.0 => ocaml-uri}/dune-project
 duniverse/{uri-sexp.3.1.0 => ocaml-uri}/uri-sexp.opam
 duniverse/{uri-sexp.3.1.0 => ocaml-uri}/uri.opam
 duniverse/{ocaml-version.2.5.0 => ocaml-version}/dune-project
 duniverse/{ocaml-version.2.5.0 => ocaml-version}/ocaml-version.opam
 duniverse/{x509.0.11.2 => ocaml-x509}/README.md
 duniverse/{x509.0.11.2 => ocaml-x509}/dune-project
 duniverse/{x509.0.11.2 => ocaml-x509}/lib/x509.mli
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/1.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/10.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/11.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/12.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/13.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/14.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/15.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/16.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/17.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/18.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/19.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/2.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/20.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/21.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/3.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/4.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/5.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/6.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/7.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/8.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/tests/crl/9.crl
 duniverse/{x509.0.11.2 => ocaml-x509}/x509.opam
 duniverse/odoc.1.5.1/test/html/highlight.pack.js
 duniverse/odoc.1.5.1/test/html/odoc.css
 duniverse/{odoc.1.5.1 => odoc}/dune-project
 duniverse/{odoc.1.5.1 => odoc}/odoc.opam
 duniverse/{odoc.1.5.1 => odoc}/src/html/tree.ml
 duniverse/{odoc.1.5.1 => odoc}/src/odoc/bin/main.ml
 duniverse/{odoc.1.5.1 => odoc}/src/odoc/etc/odoc.css
 duniverse/{odoc.1.5.1 => odoc}/src/odoc/root.ml
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+custom_theme,ml/Include/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+custom_theme,ml/Module/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+custom_theme,ml/Section/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+custom_theme,ml/Val/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Alias/X/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Alias/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Bugs/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Bugs_pre_410/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Class/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/External/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Functor/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Include/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Include2/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Interlude/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Markup/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Module/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Nested/F/argument-1-Arg1/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Nested/F/argument-2-Arg2/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Nested/F/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Nested/X/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Nested/class-inherits/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Nested/class-z/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Nested/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Nested/module-type-Y/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Recent/X/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Recent/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Recent_impl/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Section/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Stop/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Type/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/Val/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+ml/mld.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Alias/X/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Alias/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Bugs/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Bugs_pre_410/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Class/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/External/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Functor/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Include/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Include2/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Interlude/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Markup/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Module/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Nested/F/argument-1-Arg1/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Nested/F/argument-2-Arg2/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Nested/F/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Nested/X/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Nested/class-inherits/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Nested/class-z/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Nested/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Nested/module-type-Y/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Recent/X/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Recent/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Recent_impl/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Section/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Stop/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Type/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/Val/index.html
 duniverse/{odoc.1.5.1 => odoc}/test/html/expect/test_package+re/mld.html
 duniverse/odoc/test/html/highlight.pack.js
 duniverse/odoc/test/html/odoc.css
 duniverse/{patdiff.v0.13.0 => patdiff}/doc/float-tolerance.png
 duniverse/{patdiff.v0.13.0 => patdiff}/doc/refined.png
 duniverse/{pcre.7.4.3 => pcre-ocaml}/dune-project
 duniverse/{pcre.7.4.3 => pcre-ocaml}/pcre.opam
 duniverse/{pcre.7.4.3 => pcre-ocaml}/src/pcre.mli
 duniverse/{ppx_expect.v0.13.1 => ppx_expect}/example/control_chars.ml
 duniverse/ppx_inline_test.v0.13.1/dune-project
 duniverse/ppx_inline_test/dune-project
 duniverse/{ppx_inline_test.v0.13.1 => ppx_inline_test}/ppx_inline_test.opam
 duniverse/{ppxlib.0.13.0 => ppxlib}/dune-project
 duniverse/{ppxlib.0.13.0 => ppxlib}/ppxlib.opam
 duniverse/{result.1.5 => result}/dune-project
 duniverse/{result.1.5 => result}/result.opam
 duniverse/{spawn.v0.13.0 => spawn}/spawn.opam
 duniverse/{stdlib-shims.0.1.0 => stdlib-shims}/stdlib-shims.opam
 duniverse/{stringext.1.6.0 => stringext}/dune-project
 duniverse/{stringext.1.6.0 => stringext}/stringext.opam
 duniverse/{tyxml.4.4.0 => tyxml}/dune-project
 duniverse/{tyxml.4.4.0 => tyxml}/tyxml-jsx.opam
 duniverse/{tyxml.4.4.0 => tyxml}/tyxml-ppx.opam
 duniverse/{tyxml.4.4.0 => tyxml}/tyxml-syntax.opam
 duniverse/{tyxml.4.4.0 => tyxml}/tyxml.opam
 duniverse/{yojson.1.7.0 => yojson}/lib/common.ml
 duniverse/{yojson.1.7.0 => yojson}/yojson.opam
```
</details>

**Comment by emillon** [comment]
I'm not sure what needs to be done about the travis build that times out, but on the ocaml-ci side it's now working.

**Comment by yminsky** [comment]
What's next on this PR, then?

**Comment by NathanReb** [comment]
If ocaml-ci is now using the released version of opam-monorepo, I think we should simply go ahead and merge it.

From what I understood we won't be able to use travis for long anyway so relying entirely on ocaml-ci seems fine.

I'll update the readme with instructions on how to use `opam-monorepo` to manage the dependencies but this shouldn't be a blocker for the merge!

**Comment by NathanReb** [comment]
I just updated the README with instructions on how to upgrade or add dependencies.

@yminsky let me know if they are clear enough. Once this is merged I think it'd be nice to try the described workflow to upgrade JS packages from 0.13 to 0.14!

**Comment by emillon** [comment]
I think it's good to go now, the travis error was just transient.

**Pull request merged**
