### PR TITLE
Update command

### PR DESCRIPTION
**Pull request by yminsky**
Update the command directory, using dune exec and making a bunch of things deterministic.  This involved fixing some type-errors that had crept in.

### CODE REVIEW

**Comment by yminsky** [comment]
@avsm The above seems to fail because we don't have cryptokit in the duniverse. (though it oddly works on my laptop.)  Can we get cryptokit dune-ified?

**Comment by avsm** [comment]
I'm updating this PR to use `Core.Md5` instead of cryptokit.

**Comment by yminsky** [comment]
That seems fine too!

**Comment by avsm** [comment]
I don't have permissions to push to your fork, so I'll close this and have opened https://github.com/realworldocaml/book/pull/3145 as a followup

**Pull request closed without merging**
