### PR TITLE
topexpect: add support for the #show directives

### PR DESCRIPTION
**Pull request by samoht**

### CODE REVIEW

**Comment by yminsky** [comment]
What is #show? Does this relate to #typeof, which is currently used in the book?

https://github.com/realworldocaml/book/blob/d60a993bfd6b35b1fae8f609d0cef363a6eaacf6/examples/code/maps-and-hash-tables/main.mlt#L47

**Comment by samoht** [comment]
`#show` is the directive used in the usual OCaml toplevel. I am not sure what `#typeof` is but I guess it is the same thing :-) Where is this defined and what it is supposed to do?

**Comment by yminsky** [comment]
In utop, there's a #typeof directive, but no #show. We're encouraging people to use utop, so my tendency is to think we should match utop's toplevel directives. It is odd that they're different, though.

**Comment by avsm** [comment]
I think `#show` might be more modern -- it didn't exist before 4.04.0, whereas utop's `#typeof` came earlier.  The main difference seems to be that #show will follow module aliases and also doesnt require quotes around the type.

https://github.com/ocaml/ocaml/pull/520

We should probably stick to the standard toplevel where possible.  Should we consider deprecating #typeof in utop if there is no pressing need for an alternative syntax @diml @rgrinberg?

**Comment by yminsky** [comment]
Sounds fine to me. Right now, #show doesn't work at all in stop, so we'll need to add it.

**Comment by yminsky** [comment]
Never mind. #show works fine on utop. I remove all objections.

**Pull request merged**
