### PR TITLE
removed some skips

### PR DESCRIPTION
**Pull request by yminsky**

### CODE REVIEW

**Comment by yminsky** [comment]
@NathanReb This one is breaking because atdgen isn't installed.  Can you maybe separately add atdgen into the duniverse, so we can remove these skips?

**Comment by yminsky** [comment]
Ping @NathanReb.  Can we get the duniverse upgraded so that this PR will build?

**Comment by NathanReb** [comment]
Sure, I'll take a look today!

**Comment by NathanReb** [comment]
I gave it a quick look and atdgen is already in the duniverse. I think the issue here is that we can't invoke the binary from a shell block and hope it to pick up the binary from the duniverse without having dune set some env variables before.

I.e. that would work with `dune exec -- atdgen ...` but we obviously don't want that in the book as it doesn't reflect how readers would use `atdgen`.

I'll try to see what we can do here!

**Comment by yminsky** [comment]
@NathanReb Any progress on this issue?

**Comment by yminsky** [comment]
@NathanReb I've caught this up with master.  If we migrate this chapter to the new example workflow, will that fix the present problem? Or is there something else we need to do?

**Comment by avsm** [comment]
dup of #3367

**Pull request closed without merging**
