### PR TITLE
Remove some unneeded folders in examples

### PR DESCRIPTION
**Pull request by NathanReb**
Depends on #3254 

The json and command-line-parsing had all their examples grouped in a single folder within their example folder.

This PRs gets rid of this extra folder.

### CODE REVIEW

**Comment by yminsky** [comment]
It's hard to review this now, since when I look at it, github shows me some unrelated diffs that I assume are from another PR this one is based on. Do you have a recommended way of reviewing this?

**Comment by NathanReb** [comment]
It does indeed depend on #3254 and therefore contains all of its commits. You can review the last two commits which are the only ones relevant to this PR only:
- https://github.com/realworldocaml/book/pull/3256/commits/33aa20f1300641d45716c89abaef490f0791f147
- https://github.com/realworldocaml/book/pull/3256/commits/bd6bd578524d57ec10d5f47a961cf5942df0cb6c

**Comment by NathanReb** [comment]
Just rebeased this on top of master instead of #3254 so we can merge it ASAP!

**Comment by avsm** [comment]
Lgtm

**Pull request merged**
