### PR TITLE
Duniverse: Fix Records chapter tests

### PR DESCRIPTION
**Pull request by NathanReb**
Depends on #3100, I'm leaving this as draft until it's merged! Note that only the last 4 commits are relevant to this PR.

Not much going on here:
- The toplevel was missing a `#require "re"`
- I removed the deprecated `#require "re.posix"`
- I moved from the deprecated `Re.get` to `Re.Group.get`

### CODE REVIEW

**Comment by NathanReb** [comment]
Hmm this doesn't work anymore for some reason, I'll have a look!

**Comment by NathanReb** [comment]
We found the issue and have a working fix, we just need to get some dune port released to opam-overlays and it should be good!

`findlib` was silently failing because there was no `seq` library available. I'm not sure why this wasn't properly picked up when setting up the duniverse.

**Comment by NathanReb** [comment]
Fixed and updated PR description

**Comment by yminsky** [comment]
I don't know how to review this.  Github thinks 6k files have changed, which I presume is not correct...

**Comment by Julow** [comment]
That's because this PR is based on top of https://github.com/realworldocaml/book/pull/3100. It Fixes trivial things like generated files and add the duniverse, which is the source code of each dependencies.

**Comment by yminsky** [comment]
Is there a nice way in GitHub for me to read these diffs properly?

**Comment by Julow** [comment]
Yes, when #3100 is merged into the `duniverse` branch we will rebase this PRs on top of it and the diffs will be cleaner.

**Pull request merged**
