### PR TITLE
ffi: removed duplicated line

### PR DESCRIPTION
**Pull request by vitaliel**

### CODE REVIEW

**Comment by yminsky** [comment]
You can't remove the duplication, since that's the actual output of ctypes.  Maybe this is a bug in ctypes? cc @avsm @yallop

**Comment by yallop** [comment]
It looks like the duplication is from [/book/foreign-function-interface/examples/ctypes/ctypes.mli](https://github.com/realworldocaml/book/blob/bd5098445218df4d5e38e254f633a943b1dfe9af/book/foreign-function-interface/examples/ctypes/ctypes.mli#L19-L20).  Would removing it from both there and book/foreign-function-interface/README.md be sufficient?

**Comment by yminsky** [comment]
Oh, geez, yes, I'm a moron. I was imagining that was code generated by ctypes.  Sorry for wasting your time Jeremy!

So, yes, please@vitaliel, if you could fix the source file, and then do "dune runtest" to make sure everything works, and "dune promote" to update the README, everything should be good.

**Comment by vitaliel** [comment]
@yminsky 

Can you reopen PR? I modified source file too.

`dune runtest` and `dune promote` run without errors.

**Comment by avsm** [comment]
Thanks for this, @vitaliel !

**Pull request merged**
