### PR TITLE
Remove ppx jane from prelude

### PR DESCRIPTION
**Pull request by yminsky**
Remove ppx_jane and open Base from a bunch of prelude.ml files.  This required a bunch of follow-on changes to merge env's together, and to add some #require's to explicitly turn on syntax extensions.  This all seems good.

There are some weird corners, notably, for some reason ppx_sexp_conv doesn't seem to work when #require'd, but ppx_jane does.  I posted on issue there, and will fix this when that is resolved:

https://github.com/janestreet/ppx_sexp_conv/issues/30

### CODE REVIEW

**Comment by yminsky** [comment]
Note that there's a bunch of whitespace-only changes here that for some reason Github is incompetent at hiding, even when you turn on whitespace hiding.  If you look at the diff in Patdiff, everything looks fine.

**Comment by avsm** [comment]
@NathanReb there's a strange anomaly in environment variable handling.

If I run this PR with

```
env TZ=UTC dune runtest
```

...it passes the expect test.

However, forcing the env-var in either dune-workspace with:

```
(lang dune 2.0)
(env (_ (env-vars (TZ UTC))))
```

fails to force it, and the expect tests fail.

The minimal place to force the env-var to be set would be in the `dune` file for the README.md, but the `mdx` invocation doesn't allow an environment variable to be set. Would you be able to investigate this one?

**Comment by NathanReb** [comment]
Have you tried setting it with MDX labels? It should work and might be a good work around until we figured this out!

**Comment by NathanReb** [comment]
I.e. adding `,set-TZ=UTC` to the block opening line should work. There's a high chance these labels are ignored for toplevel blocks but if so, that's a bug and we should fix it!

**Comment by yminsky** [comment]
For now, I've added non-determinism markers.  We can remove them when we have a solution.

**Pull request merged**
